import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const here = path.dirname(fileURLToPath(import.meta.url));
const rootEnv = path.resolve(here, "../../.env");

// A config file turns off Prisma's own `.env` loading, so load the repo's
// root .env here for local runs. Values already in the environment win, which
// is what the containers rely on — they ship no .env file at all.
if (existsSync(rootEnv)) process.loadEnvFile(rootEnv);

const PROVIDERS = ["postgresql", "mysql"] as const;
type DbProvider = (typeof PROVIDERS)[number];

const rawProvider = process.env.DB_PROVIDER ?? "postgresql";
if (!PROVIDERS.includes(rawProvider as DbProvider)) {
  throw new Error(
    `DB_PROVIDER must be one of ${PROVIDERS.join(", ")} (MariaDB uses "mysql" — Prisma has no separate mariadb provider), got "${rawProvider}"`,
  );
}
const provider = rawProvider as DbProvider;

// schema.prisma is generated, not hand-edited: everything but the datasource
// block lives in schema.base.prisma, and the two datasource.<provider>.prisma
// files hold the couple of lines that differ. Regenerating it here means every
// Prisma command — not just a specific pnpm script — picks up DB_PROVIDER.
const prismaDir = path.join(here, "prisma");
const datasource = readFileSync(path.join(prismaDir, `datasource.${provider}.prisma`), "utf8");
const base = readFileSync(path.join(prismaDir, "schema.base.prisma"), "utf8");
writeFileSync(
  path.join(prismaDir, "schema.prisma"),
  `// GENERATED by prisma.config.ts from schema.base.prisma + datasource.${provider}.prisma.\n// Do not edit directly: edit those files and rerun a prisma command (DB_PROVIDER=${provider}).\n\n${datasource}\n${base}`,
);

/**
 * Prisma's config file, replacing the deprecated `package.json#prisma` block
 * that Prisma 7 drops.
 */
export default defineConfig({
  schema: path.join("prisma", "schema.prisma"),
  migrations: {
    // Postgres and MySQL/MariaDB DDL differ too much to share one migration
    // history, so each provider gets its own directory.
    path: path.join("prisma", provider === "mysql" ? "migrations-mysql" : "migrations"),
    seed: "tsx prisma/seed.ts",
  },
});
